[package]
name = "aleph-alpha-rag-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aleph-alpha-client = "0.7.1"
qdrant-client = "1.7.0"
tokio = "1.35.1"
